version: '3.9'

services:
  gq_backend:
    container_name: backend
    build: ./backend/
    restart: unless-stopped
    command: yarn start
    ports:
      - "3000:3000"
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - gq_mongodb

  gq_client:
    container_name: gq_client
    build: ./client/
    ports:
      - "4200:4200"
    depends_on:
      - gq_mongodb
      - gq_backend

  gq_mongodb:
    image: mongo
    restart: unless-stopped
    container_name: gq_mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    env_file:
      - .env