version: '3.9'

services:
#  backend:
#    container_name: backend
#    build: ./
#    restart: unless-stopped
#    command: yarn dev
#    env_file:
#      - .env
#    depends_on:
#      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    env_file:
      - .env
