name: Publish to NPM
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/phoqer-ui-kit
            git pull
            docker-compose stop
            docker-compose -f docker-compose.yml --env-file .env up --build --remove-orphans -d